# Generated by Django 2.0.6 on 2018-06-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.CharField(max_length=500)),
                ('ios_url', models.URLField(blank=True)),
                ('droid_url', models.URLField(blank=True)),
                ('job_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True, max_length=400)),
                ('download_url', models.URLField(blank=True)),
            ],
        ),
    ]
